- action:
  - service: script.playlist
  alias: Playlist Value Changes
  condition:
  - condition: template
    value_template: '{{ states.input_text.playlist.state != "BootValue" }}'
  id: '1521492851100'
  trigger:
  - entity_id: input_text.playlist
    from: BootValue
    platform: state
