homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 41.499
  longitude: -81.694
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 257
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
#sun:

# Weather prediction
#sensor:
#  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

#group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

input_text:
  playlist:
    name: playlist
    initial: BootValue

input_select:
  music:
    name: Music
    options:
     - " "   # Should be empty
    icon: mdi:music-note
  media_player:
    name: Media player
    options: # entity_ids of your media players
     - "soundbar"
     - "kitchen"
     - "down_stairs"
     - "bedroom"
     - "home_group"
     - "up_stairs"
     - "front_living_room"
     - "basement"
     - "guest_room"
    icon: mdi:music-note

switch:
 - platform: gmusic
   user: !secret gmusic_user
   password: !secret gmusic_pass
   device_id: !secret gmusic_device_id # http://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.login
   media_player: media_player # entity id of the input select used for mediaplayer
   playlist: music # entity id of the input select used for playlist

# OPTIONAL
group:
  google_music:
    name: Google Music
    entities:
    - input_select.music
    - input_select.media_player
    - switch.google_music




